version: '3.8'

services:
  fastapi:
    container_name: apptesting
    build: .  # Builds using Dockerfile in current directory
    ports:
      - "8001:8001"
    volumes:
      - ./app:/app  # Mounts host directory to container
